services:
  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper
    restart: always
    ports:
      - "127.0.0.1:2181:2181"
    volumes:
      - zk-logs:/logs
      - zk-data:/data
      - zk-datalog:/datalog

  nimbus:
    image: storm:2.8.8
    container_name: nimbus
    command: storm nimbus
    depends_on:
      - zookeeper
    restart: always
    volumes:
      - storm-nimbus-logs:/logs

  supervisor:
    image: storm:2.8.8
    container_name: supervisor
    command: storm supervisor
    depends_on:
      - nimbus
      - zookeeper
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - storm-supervisor-logs:/logs
      - ${PWD}/hostnames.gz:/mnt/hostnames.gz:ro # Read-only mount

  ui:
    image: storm:2.8.8
    container_name: ui
    command: storm ui
    depends_on:
      - nimbus
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - storm-ui-logs:/logs

  opensearch-node1: # This is also the hostname of the container within the Docker network (i.e. https://opensearch-node1/)
    image: opensearchproject/opensearch:2.19.5 # Specifying the latest available image - modify if you want a specific version
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - node.name=opensearch-node1 # Name the node that will run in this container
      - discovery.seed_hosts=opensearch-node1 # Nodes to look for when discovering the cluster
      - cluster.initial_cluster_manager_nodes=opensearch-node1 # Nodes eligible to serve as cluster manager
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g" # Set min and max JVM heap sizes to at least 50% of system RAM
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data # Creates volume called opensearch-data1 and mounts it to the container
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    # restart: always

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.19.5 # Make sure the version of opensearch-dashboards matches the version of opensearch installed on other nodes
    container_name: opensearch-dashboards
    ports:
      - 5601:5601 # Map host port 5601 to container port 5601
    expose:
      - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch-node1:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true" # disables security dashboards plugin in OpenSearch Dashboards
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    # restart: always

volumes:
  opensearch-data1:
  storm-ui-logs:
  storm-nimbus-logs:
  storm-supervisor-logs:
  zk-logs:
  zk-data:
  zk-datalog:
